src/asgard/locations/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('asgard.locations.views',
	url(r'^(?P<city>[-\w]+)/(?P<location>[-\w]+)/$',
		view = 'detail',
		name = 'locations_detail',
	),
	url(r'^(?P<city>[-\w]+)/$',
		view = 'city',
		name = 'locations_city',
	),
	url(r'^$',
		view = 'index',
		name = 'locations_index',
	)
)

src/asgard/locations/models.py
from django.db import models
from django.db.models import permalink
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save, post_delete
from django.contrib.auth.models import User

from asgard.locations.managers import LocationManager, PointManager

class PlaceType(models.Model):
	""" Place types """
	title = models.CharField(_('title'), max_length=100, unique=True)
	slug = models.SlugField(_('slug'), unique=True)
	
	class Meta:
		verbose_name = _('place type')
		verbose_name_plural = _('place types')
		db_table = 'location_types'
	
	def __unicode__(self):
		return u"%s" % self.title

class City(models.Model):
	""" City model """
	city = models.CharField(_('city'), max_length=100)
	province = models.CharField(_('province'), max_length=100)
	country = models.CharField(_('country'), max_length=100)
	slug = models.SlugField(_('slug'), unique=True)
	
	class Meta:
		verbose_name = _('City')
		verbose_name_plural = _('Cities')
		db_table = 'location_cities'
		unique_together = (('city', 'province',),)
		ordering = ('province', 'city',)
	
	@permalink
	def get_absolute_url(self):
		return ('locations_city', None, {
			'city': self.slug,
		})
	
	def __unicode__(self):
		return u"%s, %s" % (self.city, self.province)

class Point(models.Model):
	""" Point model """
	latitude = models.FloatField(_('latitude'), blank=True, null=True)
	longitude = models.FloatField(_('longitude'), blank=True, null=True)
	address = models.CharField(_('address'), max_length=200, blank=True)
	city = models.ForeignKey(City)
	postal_code = models.CharField(_('postal code'), max_length=10, blank=True)
	woeid = models.IntegerField(_('WOEID'), blank=True, null=True)
	
	objects = PointManager()
	
	class Meta:
		verbose_name = _('Point')
		verbose_name_plural = _('Points')
		db_table = 'location_points'
	
	def __unicode__(self):
		return u"%s" % self.address
	
	def full_address(self):
		return u"%s %s %s %s %s" % (self.address, self.city.city, self.postal_code, self.city.province, self.city.country)

class Location(models.Model):
	title = models.CharField(_('Title'), max_length=200)
	slug = models.SlugField(_('Slug'), max_length=50)
	
	unit = models.CharField(_('unit'), blank=True, max_length=100, help_text='Suite or Apartment #')
	phone = models.CharField(_('phone'), blank=True, max_length=20)
	url = models.URLField(_('url'), blank=True, verify_exists=False)
	email = models.EmailField(_('email'), blank=True)
	description = models.TextField(_('description'), blank=True)
	
	point = models.ForeignKey(Point)
	
	objects = LocationManager()
	
	date_added = models.DateTimeField(_('date added'), auto_now_add=True)
	date_modified = models.DateTimeField(_('date modified'), auto_now=True)
	
	class Meta:
		verbose_name = _('Location')
		verbose_name_plural = _('Locations')
		db_table = 'locations'
	
	@permalink
	def get_absolute_url(self):
		return ('locations_detail', None, {
			'location': self.slug,
			'city': self.city_slug,
		})
	
	def __unicode__(self):
		return u"%s" % self.title

src/asgard/locations/forms.py
"""
Copyright (C) 2008 Myles Braithwaite

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
	
	http://www.apache.org/licenses/LICENSE-2.0
	
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django import forms

class LocationForm(forms.Form):
	place = forms.CharField()

src/asgard/locations/views.py
from datetime import datetime

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import Http404
from django.core.paginator import Paginator, InvalidPage, EmptyPage

from asgard.locations.models import *

def index(request, context={}, template_name='locations/index.html'):
	locations = Location.objects.all()
	
	context.update({
		'locations': locations,
	})
	
	return render_to_response(template_name, context, context_instance=RequestContext(request))

def city(request, city, context={}, template_name='locations/city.html'):
	try:
		city = City.objects.get(slug=city)
	except City.DoesNotExist:
		raise Http404
	
	context.update({
		'city': city
	})
	
	return render_to_response(template_name, context, context_instance=RequestContext(request))

def detail(request, location, city, context={}, template_name='locations/detail.html'):
	try:
		location = Location.objects.get(slug=location)
	except Location.DoesNotExist:
		raise Http404
	
	context.update({
		'location': location,
	})
	
	return render_to_response(template_name, context, context_instance=RequestContext(request))

src/asgard/locations/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}Asgard{% endblock %}</title>
</head>
<body id="{% block body_id %}{% endblock %}">
	<div id="body">
		{% block body %}
		<div>
			{% block content_title %}{% endblock %}
		</div>
		<div id="content">
			{% block content %}{% endblock %}
		</div>
		{% endblock %}
	</div>
</body>
</html>

src/asgard/locations/templates/locations/base_locations.html
{% extends "base.html" %}

src/asgard/locations/templates/locations/city.html
{% extends "locations/base_locations.html" %}

{% block title %}{{ block.super }}: {{ city }}{% endblock %}

{% block content_title %}
	<h2>{{ city }}</h2>
{% endblock %}

{% block content %}
	<ul class="link_list">
		{% for point in city.point_set.all %}{% for location in point.location_set.all %}
			<li id="location_{{ location.id }}">
				<a href="{{ location.get_absolute_url }}">{{ location.title }}</a>
			</li>
		{% endfor %}{% endfor %}
	</ul>
{% endblock %}

src/asgard/locations/templates/locations/detail.html
{% extends "locations/base_locations.html" %}

{% block title %}{{ block.super }}: {{ location.title }}{% endblock %}

{% block content_title %}
	<h2>{{ location.title }}</h2>
{% endblock %}

{% block content %}
	{{ description|safe }}
	
	<h3>Address</h3>
	<p>
		{% if location.point.address %}{{ location.point.address }},<br>{% endif %}
		{% if location.unit %}{{ location.unit }}<br>{% endif %}
		{{ location.point.city }}
		{% if location.point.postal_code %}{{ location.point.postal_code }}{% endif %}<br>
		{{ location.point.city.country }}
	</p>
	
	{% if location.phone or location.url or location.email %}
		<h3>Contact</h3>
		<dl>
			{% if location.phone %}
				<dt>Phone number</dt>
				<dd>{{ location.phone }}</dd>
			{% endif %}
			{% if location.url %}
				<dt>Website</dt>
				<dd><a href="{{ location.url }}" title="{{ location.title }} website">{{ location.url }}</a></dd>
			{% endif %}
			{% if location.email %}
				<dt>Email</dt>
				<dd><a href="mailto:{{ location.email }}" title="{{ location.title }} email">{{ location.email }}</a></dd>
			{% endif %}
		</dl>
	{% endif %}
{% endblock %}

src/asgard/locations/templates/locations/index.html
{% extends "locations/base_locations.html" %}

{% block title %}{{ block.super }}: Locations{% endblock %}

{% block content_title %}
	<h2>Locations</h2>
{% endblock %}

{% block content %}
	<ul>
		{% for location in locations %}
			<li id="location_{{ location.id }}">
				<a href="{{ location.get_absolute_url }}">{{ location.title }}</a>
			</li>
		{% endfor %}
	</ul>
{% endblock %}